In [ ]:
#importing
import numpy as np

Arrays


In [ ]:
#creating 1D array
A=np.array([1,2,3,4,5])
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
#creating a 2D array
B=np.array([[2,3,4],[7,8,9]])
print(B)

[[2 3 4]
 [7 8 9]]


In [ ]:
#creating a 3D array
C=np.array([[[2,3,4],[5,6,7]],[[1,8,9],[0,4,5]]])
print(C)

[[[2 3 4]
  [5 6 7]]

 [[1 8 9]
  [0 4 5]]]


In [ ]:
#checking dimensions
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3


In [ ]:
D=np.ones((2,3,2)) #groups,row,columns,3D
print(D)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
#ones
E=np.ones((3,2)) #rows,columns,2D
print(E)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Zeros
F=np.zeros((3,2))  #2D
print(F)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
J=np.eye(4)
print(J)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#arange
H=np.arange(3,31,3) #start,stop,step
print(H)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
#arange with reshape
H=np.arange(3,31,3).reshape(5,2)
print(H)


[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
V=np.linspace(12,24,10)
print(V)

[12.         13.33333333 14.66666667 16.         17.33333333 18.66666667
 20.         21.33333333 22.66666667 24.        ]


In [ ]:
L=np.arange(1,7).reshape(2,3)
print(L)
R=np.arange(9,15).reshape(2,3)
print(R)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [ ]:
print(L+R)

[[10 12 14]
 [16 18 20]]


In [ ]:
G=np.sum((L,R))
print(G)

90


In [ ]:
G=np.sum((L,R),axis=1)
print(G)

[[ 5  7  9]
 [21 23 25]]


In [ ]:
M=np.linspace(1,2,6)
print(M)

[1.  1.2 1.4 1.6 1.8 2. ]


In [ ]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=0))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A*B)

[[2 0]
 [0 4]]


In [ ]:
print(A@B)

[[5 4]
 [3 4]]


In [ ]:
#b=np.array[25,289,361,81]  find square root and iterate through result values output 5 square is 25 by using np.sprt
b=np.array([25,289,361,81])
for i in b:
  print(int(np.sqrt(i)),"square is",i)

5 square is 25
17 square is 289
19 square is 361
9 square is 81


Array joining

In [ ]:
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b)))
print("\n")
print(np.hstack((a,b)))

[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("output of dstack")
print(np.dstack(a))
#no.of rows becomes no.of groups
#columns becomes rows
#group becomes columns

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
output of dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
