In [ ]:
import numpy  as np
#RANDAM MODULE IS SUB-PACKAGE OF NUMPY

In [ ]:
a=np.random.rand(1)
print(a)

[0.4129954]


In [ ]:
a=np.random.rand(8,4) #rand-range is between 0 and 1
print(a)

[[0.65696219 0.6252774  0.45638244 0.78787952]
 [0.3636599  0.75503307 0.33269468 0.40288753]
 [0.49681613 0.34504055 0.54629866 0.85292634]
 [0.77313864 0.61875156 0.47890893 0.29071772]
 [0.7220594  0.98253707 0.18198261 0.60378397]
 [0.90106562 0.13138791 0.57771064 0.76532208]
 [0.81810156 0.0240736  0.87366381 0.15627585]
 [0.84754495 0.48981142 0.33568782 0.62718476]]


In [ ]:
a=10*np.random.rand(8,4)
print(a)

[[8.37617037 4.72950721 1.52030707 2.8164432 ]
 [0.81801283 8.07224151 5.72863299 6.99109457]
 [9.22744077 3.06446052 5.61352504 4.14330556]
 [8.94177903 6.19193876 7.21473033 4.91645671]
 [7.9135338  4.25452468 4.44628901 9.52720598]
 [4.13467272 0.74987654 5.65983442 6.06716923]
 [4.1720303  7.17961804 8.22108265 0.21707023]
 [6.77830939 2.71120785 3.57534116 9.14136424]]


In [ ]:
a=np.eye(4,8)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


In [ ]:
a=np.floor(10*np.random.rand(8,4))
print(a)

[[0. 8. 9. 4.]
 [3. 8. 1. 0.]
 [8. 3. 8. 6.]
 [6. 6. 1. 9.]
 [4. 4. 6. 8.]
 [9. 2. 7. 7.]
 [3. 8. 8. 2.]
 [1. 9. 7. 9.]]


In [ ]:
A=np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(A,4) #vsplit split the array from top to bottom

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,3)

ValueError: array split does not result in an equal division

In [ ]:
np.vsplit(A,(2,7))

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28]]),
 array([[29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(3,5)) #spilt it after 3-row and 5-row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
a=np.arange(1,33).reshape(4,8)
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(a,4) #spliting takes frome left to right

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(a,(3,7)) #spliting takes place after 3rd column and 7th column

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

In [ ]:
np.hsplit(a,(2,5))

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5],
        [11, 12, 13],
        [19, 20, 21],
        [27, 28, 29]]),
 array([[ 6,  7,  8],
        [14, 15, 16],
        [22, 23, 24],
        [30, 31, 32]])]

Trignometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
B=np.rad2deg(A) #convert radians to degrees

In [ ]:
np.deg2rad(B) #convert degrees to radians

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(1) #radians

0.8414709848078965

In [ ]:
np.cos(1) #radians

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

statistics

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(C) #for inverse matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=np.floor( 10*np.random.rand(24).reshape(6,4))
print(C)

[[2. 6. 2. 0.]
 [8. 7. 5. 4.]
 [4. 8. 5. 5.]
 [0. 1. 0. 3.]
 [1. 0. 5. 2.]
 [5. 1. 0. 2.]]


In [ ]:
print(np.argmax(C))

4


In [ ]:
C= 10*np.random.rand(24).reshape(6,4)
print(C)

[[4.50025637 2.29861147 1.90094326 6.17399701]
 [0.0916677  6.35301816 2.56821765 8.22641779]
 [2.57067468 1.53460763 4.20516874 8.80319893]
 [6.43852647 0.52884109 4.33261296 8.22968635]
 [4.97501296 2.46955349 3.29256969 3.89960337]
 [2.85461246 7.68971909 1.01353437 6.14318265]]


In [ ]:
print(np.argmax(C))

11


In [ ]:
print(np.argmax(C,axis =1))

[3 3 3 3 0 1]


In [ ]:
print(np.argmax(C,axis =0))

[3 5 3 2]


In [ ]:
print(np.argmin(C,axis =1))

[2 0 1 1 1 2]


In [ ]:
print(np.argmin(C,axis =0))

[1 3 5 4]


searching

In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))
print(np.where(a%2==1))

(array([0, 1, 4]),)
(array([2, 3, 5]),)


In [ ]:
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [ ]:
a=np.array([6,7,8,9,10])
X=np.searchsorted(a,10)
print(X)

4


In [ ]:
a=np.array([6,7,8,3,10])
X=np.searchsorted(a,3)
print(X)

0


In [ ]:
a=np.array(['banana','cherry','apple'])
print(np.sort(a))

['apple' 'banana' 'cherry']


In [ ]:
a=np.array(['true','false','true'])
print(np.sort(a))

['false' 'true' 'true']


In [ ]:
b=np.array([[3,2,4],[5,0,1]])
print(np.sort(b))

[[2 3 4]
 [0 1 5]]


filtering

In [ ]:
b=np.array([40,43,50,44,67,78]) #flit may b e list or array
filt=np.where(b%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
b[filt]

array([40, 50, 44, 78])

Iterating through two arrays

In [ ]:
names=np.array(["sudha","raji","susmi","valli"])
initials=np.array(["m","d","u","p"])
for i,j in zip(initials,names):
  print(i,".",j)


m . sudha
d . raji
u . susmi
p . valli


In [ ]:
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,22,23,24,25])
n=np.multiply(a,b)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,22,23,24,25])
n=np.divide(a,b)
print(n)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,22,23,24,25])
n=np.mod(a,b)
print(n)

[10 20  8 17  2 10]


In [ ]:
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,22,23,24,25])
n=np.divmod(a,b)
print(n)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


Logrithms

In [ ]:
a1=np.arange(1,10)
print(a)
print(np.log2(a1))

[10 20 30 40 50 60]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
a=1.2
print(np.log(a)) #log base e

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a))#log base 2

0.2630344058337938


In [ ]:
a=1.2
print(np.log10(a))#log base 10

0.07918124604762482


In [ ]:
a=np.array([1,1.2,3,4])
print(np.log(a)) #natural  log e

[0.         0.18232156 1.09861229 1.38629436]


other mathmatical functions

In [ ]:
c=np.array([5,6,3,8])
print(np.cumprod(c))

[  5  30  90 720]


In [ ]:
c=np.array([5,6,3,8])
print(np.sum(c))

22


In [ ]:
a=np.array([10,15,25,15])
n=np.diff(a)
print(n)

[  5  10 -10]


In [ ]:
a=455
b=665
print(np.lcm(a,b))

8645


In [ ]:
a=455
b=665
print(np.gcd(a,b))

35


In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a) #takes multiple gives single output
print(gc)

3


In [ ]:
a=np.array([12,15,60])
lc=np.lcm.reduce(a) #takes multiple gives single output
print(lc)

60
